### ISSUE TITLE
Update MoPub adapter to support MoPub SDK 5.9.0

### ISSUE THREAD

**Issue by stsandro** [googleads/googleads-mobile-ios-mediation#155]
Is there a plan to update the MoPub adapter to support the current release of the MoPub SDK 5.9.0? The currently supported MoPub SDK is 5.7.1 which was released on June 3, 2019. The adapter is now 3 months behind. I would really love to update to MoPub 5.9.0, because it has several improvements and supports iOS 13 as well.

Kind regards,
Sandro

**Comment by maninomula** [comment]
We are actively working on this issue. We reach out again once we have any update.

**Comment by gonzajg** [comment]
Hi, any news on this?

**Comment by marco-fing** [comment]
@maninomula Thanks for that. +1 here to get a version that would be compatible with latest 5.9.0 MoPub version

**Comment by polmum** [comment]
Hello
Any ETA on this? Older versions of MoPub have some crashes when building for iOS 13, so an update would really help.

**Comment by AndrewTerekhine** [comment]
+1 Moreover, Apple flags apps that use AdMob MoPub Adapter because it links to outdated MoPub based on UIWebView. Here is the part of a warning from Apple: "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview" 
I hope this issue will be fixed soon as the only choice for us now is to drop this AdMob MoPub Adapter from all the affected apps.

**Comment by charliefancelli** [comment]
Now you can work on 5.10.0 support...

**Comment by stsandro** [comment]
I think we can close this issue now.

Thanks to everyone for their efforts. 🙏
