### ISSUE TITLE
Old Facebook Adapters versions were deleted

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#209]
Hey,
A bunch of old facebook adapters were deleted. It is understandable if you find a problem that needs fixing, but you should never delete an already published podspec. We now have tagged versions of our apps that no longer build, and this should never happen.
You should publish the new version, and ask users to update.

![image](https://user-images.githubusercontent.com/19226232/78599686-f6ece780-7827-11ea-8788-e3aabc18a524.png)

**Comment by jjhampton** [comment]
@ericleich I see you marked the deleted Podspecs as deprecated [here](https://github.com/googleads/googleads-mobile-ios-mediation/commit/6130adf7edd624039445f5ac91a8545d5b10dffc) . 

Will these Podspecs ever be restored? Newer versions of our apps do not use these deprecated Podspecs, but we have some older versions of our apps that can no longer build due to this sudden and unexpected breaking change.

**Comment by ericleich** [comment]
We did remove versions 5.6.1.0 - 5.8.0.0 intentionally, and do not plan to restore these versions. We recommend updating your adapter dependency to version 5.8.0.1.

**Comment by polmum** [comment]
This issue is not only about restoring missing adapter versions. It is also about going against good, established practices by deleting older podspecs and making old builds fail. You should have been aware that most projects don't check in their pods folder and that as a consequence this was going to happen.
I really encourage you for future similar issues to just release a new version without deleting older ones.
