### ISSUE TITLE
Mopub adapter freeze iOS on app startup

### ISSUE THREAD

**Issue by neobie** [googleads/googleads-mobile-ios-mediation#212]
I notice Mopub iOS sdk 5.10 cause some devices like iPhone 6, iPhone 7 with iOS13.3+ to hang when app is opened.
Disabling mopub medation in Admob doesn't help.

If I integrate Mopub iOS sdk 5.10 alone, crash doesn't happen.

This is not the first time I have such issue. Numerous issues happen too with Android. And it is very hard to debug without proper device model.

Who should be responsible for the crash ? The admob adapter or the Mopub sdk ? 

Why disabling the mediation in Admob doesn't help ? It needs to be if there are so many unknown bugs with the Mediation adapters and not tested properly ?

**Comment by ericleich** [comment]
@neobie Crashes/hangs could be a result of the Google adapter for MoPub or the underlying MoPub SDK. With crashes, it's usually pretty easy to tell given a trace. "freezes" are harder to debug. It would help if you could provide more information as to what's happening. Is it a crash or the app is freezing? Do you have a stack trace to share?

The adapter code is [available as open source](https://github.com/googleads/googleads-mobile-ios-mediation/tree/master/adapters/MoPub/MoPubAdapter). The adapter essentially does the MoPub SDK integration on your behalf. If you've integrated MoPub SDK directly yourself, the code may be familiar to you as to how the adapter is requesting MoPub ads.

As for turning off the adapter, there is an [initialization](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/MoPub/MoPubAdapter/GADMediationAdapterMoPub.m#L16-L34) call that happens when your app initializes the Google Mobile Ads SDK. Using the AdMob app ID you provide, the SDK queries all ad units for that app, all mediation groups targeted to that ad unit, the network configurations for MoPub associated with each of those mediation groups, and lets MoPub know which configurations they can expect a request for. That said, if you have any active MoPub line item configured inside any mediation group targeted to any ad unit that's part of the AdMob App ID you specified, this code gets called.

Around the time we migrated to MoPub SDK 5.11, we did fix a crash that occurred if MoPub SDK was initialized for the first time off the main thread. See https://github.com/googleads/googleads-mobile-ios-mediation/commit/ec8e473ffaa6cedc13bc86fd3fdbe64770a7fe07. This is something we first noticed when updating support for their 5.11 SDK. This very well might have been your issue.
