### ISSUE TITLE
Could you publish the latest version of I-Mobile adapter to the central pods?

### ISSUE THREAD

**Issue by pot8os** [googleads/googleads-mobile-ios-mediation#213]
Hello,

I installed `GoogleMobileAdsMediationIMobile` via `Cocoapods` as follows.
```ruby
pod 'GoogleMobileAdsMediationIMobile'
```
However as of today it gets `2.0.29.0` from [the central Pods repo](https://cocoapods.org/) even though this repo [released `2.0.31.0` already](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/I-Mobile/CHANGELOG.md#i-mobile-ios-mediation-adapter-changelog).
```markdown
  - GoogleMobileAdsMediationIMobile (2.0.29.0):
    - Google-Mobile-Ads-SDK (>= 7.52.0)
    - ImobileSdkAds (= 2.0.29)
```
<img width="1223" alt="Screen Shot 2020-04-18 at 9 45 34" src="https://user-images.githubusercontent.com/5249113/79624052-3259b100-815a-11ea-98e2-10d77762edcf.png">

`2.0.31.0` removes `UIWebView` dependency so we need it as soon as possible to comply with the Apple's policy.
 
Thanks!

**Comment by smartestapps** [comment]
If you need it as soon as possible, then I recommend downloading the adapter directly from their bintray and adding it to your project manually instead of going through cocoapods.

Here's a link to their zip file of the adapter framework: https://bintray.com/google/mobile-ads-adapters-ios/download_file?file_path=IMobileAdapter%2F2.0.31.0%2FIMobileAdapter-2.0.31.0.zip

**Comment by ericleich** [comment]
Sorry for the delay @pot8os, this is live on CocoaPods now - https://github.com/CocoaPods/Specs/blob/master/Specs/7/b/b/GoogleMobileAdsMediationIMobile/2.0.31.0/GoogleMobileAdsMediationIMobile.podspec.json

Friendly note - due to our release process, it is possible for a [changelog](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/I-Mobile/CHANGELOG.md#i-mobile-ios-mediation-adapter-changelog) to be updated prior to the release going out. However, CocoaPods and [Bintray](https://bintray.com/google/mobile-ads-adapters-ios/IMobileAdapter) release are usually paired together, I'm not sure what happened here.

Thanks for helping to resolve @smartestapps !
