### ISSUE TITLE
M1 Apple Silicon Support for Facebook Adapter

### ISSUE THREAD

**Issue by kevinchau** [googleads/googleads-mobile-ios-mediation#284]
The current version of the Facebook Adapter can't be used for running on the iOS Simulator on arm64, it will throw this error message during buildtime:

```
ld: in /Users/kevinchau/Documents/dev/radioapp-ios/Pods/GoogleMobileAdsMediationFacebook/FacebookAdapter-6.2.0.0/FacebookAdapter.framework/FacebookAdapter(GADFBNativeBannerAd.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/kevinchau/Documents/dev/radioapp-ios/Pods/GoogleMobileAdsMediationFacebook/FacebookAdapter-6.2.0.0/FacebookAdapter.framework/FacebookAdapter' for architecture arm64
```

The AdMob framework now supports M1 mac. When will the facebook adapter support it?

**Comment by chlandacastro** [comment]
Hello Kevinchau!  Thanks for let us know about this issue.  We will be working on it. 
Regards, 
Christian.

**Comment by ericleich** [comment]
Hey Kevin, after looking into this further, the Facebook Audience Network SDK still doesn't support arm64 simulator. So this blocks us from releasing a compatible arm64 simulator slice on the adapter.

**Comment by ericleich** [comment]
Closing this since we can't update now. [Facebook Audience Network 6.3.0](https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.3.0/FBAudienceNetwork.podspec.json#L19), the current latest SDK, still releases a .framework and not a .xcframework, so there's no way they can be providing an arm64 simulator architecture since the arm64 arch in that framework will be for devices.

Once the Facebook Audience Network SDK adds arm64 simulator, we'll be able to do the same in our next adapter update.
