### ISSUE TITLE
Relax adapters dependency on Google-Mobile-Ads-SDK version

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#304]
Hey,
I've noticed that whenever a new version of Google-Mobile-Ads-SDK is released, all new adapters versions from that moment onwards are released with a dependency greater or equal to the latest Google-Mobile-Ads-SDK release.
I was wondering if that is really necessary. I find that dependency too restrictive, forcing me to update Google-Mobile-Ads-SDK when I might just want to update only an adapter (because it might me crashing for example).
I believe that the adapter dependency should only be updated when Google-Mobile-Ads-SDK releases a version with breaking changes. Would you give this some thought?

Thanks

**Comment by ericleich** [comment]
You're correct that it's not always necessary. But we test the adapters against the latest SDK, and trying to keep track of min supported version for each adapter would require (at least) double the testing cycles, to test against latest, min, and work to figure out new min if min breaks something. The thought is also that if you're updating adapters to the latest, it's probably an "SDK update cycle" and you can update Google-Mobile-Ads-SDK to the latest.

I understand the Google-Mobile-Ads-SDK version 8.0 update may have been particularly cumbersome as that was a breaking change, which is a bit unfortunate. But updating min-adapter dependency on Google-Mobile-Ads-SDK happens more than you might think.

- Version 7.42.0 added new rewarded mediation APIs. When adapters updated to use those, it forced a dep update even if your app doesn't use rewarded.
- Version 7.48.0 had a rewarded mediation bug. That's not actually a strict dep requirement, but we'd probably wanted to have gotten all users off that version if they were mediating. Something similar happened in 7.53.1.
- Sometimes even publisher-level APIs affect mediation adapter requirements. Some adapters read the `GADMobileAds.sdkVersion` API for logging/debugging purposes, so when that API changed in version 8.0.0, adapters had to depend on version 8.0.0 anyways even though we tried to leave the mediation interfaces unaffected. This happened a few other times for minor 7.x updates though I can't recall the exact specific examples.

So, partially to simplify testing, but also to try and improve the happy path by directing users away from potential older SDK bugs, has made adapter releases a bit more restrictive than they need to be. However, it puts your code in a better tested state, and you mentioned that the reason you update 3p adapters is to resolve other bugs, which this approach aims to do too. There are no current plans to revert this back.

For the power users with custom needs, I unfortunately couldn't find an easy way to have your podspec override a min version. Maintaining your own copies of podspecs or using manual downloads altogether are workarounds, although admittedly put more burden on you.

**Comment by polmum** [comment]
Thanks for the answer, I really appreciate you taking your time to provide me with details behind your update reasoning!
I agree that it simplifies testing and the happy path. Also, I was not suggesting never to do this, because for instance I agree with the logic of wanting users off a version with a bug.
What I don't agree with entirely is the fact that, as you said it, there have been minor version updates with breaking changes. I know that changing this would not be easy, but you could limit breaking changes to only major version updates (following semantic versioning), and make adapters depend only on major Google-Mobile-Ads-SDK versions (for instance, `"Google-Mobile-Ads-SDK": "~> 8.0"`).
Again, I know this would not be an easy change, but I think that being explicit about major changes following semantic versioning would be the best way to go with this. Hopefully you can give it some thought.

Thanks

**Comment by ericleich** [comment]
@polmum The versioning question is interesting too. Per [adapter versioning](https://developers.google.com/admob/ios/mediate#adapter_versioning), the adapter versions mimic the 3rd party SDK version they wrap. We do this intentionally to make it very clear which adapter version should be used with the 3p SDK version, at the cost of making adapters not semantic with respect to every dependency they use (namely, the Google Mobile Ads SDK).

For reasons discussed above, we push forward the Google Mobile Ads SDK version on future adapter releases. We could consider using `~>` instead of `>=` for the dp, but I don't think that solves the initial problem you had. For example, let's say we made adapters from a couple months ago depends on `~> 7.68`. The next version we're doing today will still be `~> 8.3`. When you update to the latest adapter, it'll still require 8.3 Google Mobile Ads SDK.

What `~>` would solve is somebody using 2 month old adapter wouldn't accidentally get pushed to 8.0 when running pod update, which may put them in an incompatible state. That's a risk, but one could at least work around that in their podfile by explicitly requesting a 7.69.0 version. `~>` is actually more restrictive though -- it wouldn't let you use version 8.0 with an old adapter, even if that old adapter was actually still compatible with 8.0.

So to be clear, are you suggesting that moving to `~>`, which is more restrictive, is worth that cost for better user experience for those on old adapters? I agree that it's slightly better to do that from a semantic versioning perspective, and the only cost to us would be that for any future major SDK release we do, we will need to make sure to fast follow 16 adapter releases so anybody updating to version 8 can have a compatible adapter to work with. Note that it would also then force you to update every adapter as well, and deal with potential bugs in a 3p SDKs latest version. Also for context, for Google SDK version 8.0.0, only ~4-5 adapters were "broken" because they happened to log `[GADRequest sdkVersion]` which got renamed. The mediation adapter interfaces were preserved across our major version and so most adapters were unaffected.

**Comment by polmum** [comment]
You are right in that it would be more restrictive. It would prevent the issue that happened with `[GADRequest sdkVersion]` as you mentioned, but perhaps it is too restrictive unnecessarily.
Following your example, I wouldn't update the dependency to `~> 8.3`, I would depend on `8.0`, unless the adapter depended on a new feature in that minor release. I know you test the integration against the latest Google version, but if that latest version is a minor or a patch, there should be no breaking changes so ideally no need to update the adapter dependency.
Again, I know changing your release process is not easy, so I'm not suggesting you do so. I just wanted to see if it was feasible and if it made sense.

**Comment by ericleich** [comment]
Regarding my earlier comment, https://github.com/googleads/googleads-mobile-ios-mediation/issues/312 is an example of th exact crash that results from using `>=`, so that theoretical problem is real. While more restrictive, `~>` probably is the right answer and we'll consider this.

Regarding the change you want from this issue, the examples I listed earlier (7.42.0, 7.48.0) were examples where we need an update on min version. Even though `Google-Mobile-Ads-SDK` itself has no breaking change, the adapter used a feature in the newer version that didn't exist in `7.0.0`. It's not too hard to check for a compilation failure (the 7.42.0 API addition would be quick to catch via a compile check against 7.0.0). But any bugs in older SDKs would not be caught by a compile-time check. I'm still a bit resistant to changing the process here, but will keep this open a bit longer to think about it some more and get some other internal stakeholder opinions on value vs. maintenance cost.

**Comment by polmum** [comment]
Great! Regardless of your final decision, thanks a lot for taking your time to consider this!

**Comment by ericleich** [comment]
After further discussion, we've decided to relax back to `~> 8.0` going forward. You'll see this in future adapter releases. If we determine one day that version 9 is backwards compatible, we'll change to something like `>=8.0, < 10` to enable further flexibility.

Bumping the min for compile verification will be best effort until we can set up some automation for that. Bumping min due to SDK mediation bugs won't happen, and it will be best practice to use at least the GMA SDK that was tested against that adapter version, which is in the release notes.

**Comment by polmum** [comment]
Great news! I really think that this will be a change for the best.
Thanks a lot for your time and effort!
