### ISSUE TITLE
Crash on integrating GADMediationAdapterFacebook

### ISSUE THREAD

**Issue by sotrosh** [googleads/googleads-mobile-ios-mediation#312]
Hello Google Team,

Based on [Google Mediation Tutorial](https://developers.google.com/admob/ios/mediation/facebook) I integrated Facebook mediation and seems it crashes at iOS app startup:

> ["GADMobileAds": <GADAdapterStatus: 0x283601110; state = Ready>, "GADMediationAdapterFacebook": <GADAdapterStatus: 0x2836e8e70; state = Not Ready;Adapter failed to initialize. Adapter raised an exception during setup. Adapter: GADMediationAdapterFacebook, Exception: +[GADRequest sdkVersion]: unrecognized selector sent to class 0x100b7bd60>]

As result I get zero ad impressions from Facebook (Admob only)

How to resolve the issue above?

Attaching my Podfiles. 
[Podfile.lock.txt](https://github.com/googleads/googleads-mobile-ios-mediation/files/6332874/Podfile.lock.txt)
[Podfile.txt](https://github.com/googleads/googleads-mobile-ios-mediation/files/6332875/Podfile.txt)

Also there is similar issue on stack overflow created days ago: 
https://stackoverflow.com/questions/66998951/app-crashes-aftter-adding-admob-mediation-facebook

**Comment by ericleich** [comment]
The Facebook adapter does read the Google Ads SDK version, who's API changed n version 8.0.0. The Facebook adapter was only built against 8.0.0 since version 6.2.1.1 according to the [changelog](https://developers.google.com/admob/ios/mediation/facebook#version-6.2.1.1).

Your app has Google-Mobile-Ads-SDK 8.3.0 and Facebook adapter 5.10.1.1, which is an invalid configuration. Unfortunately, the way the dependencies are defined allow that configuration to happen, and that's something we should look into fixing. In the meantime, if you run `pod update` to get the latest version of the FB adapter, or change your podfile to explicitly request a 7.x copy of the Google SDK:

```
    pod 'Google-Mobile-Ads-SDK', '7.69.0'
    pod 'GoogleMobileAdsMediationFacebook'
```

that should address your issue.

**Comment by sotrosh** [comment]
@ericleich Thank you for quick response.

> if you run pod update to get the latest version of the FB adapter, or change your podfile to explicitly request a 7.x copy of the Google SDK:
Not sure what you mean by "get the latest version of the FB adapter". I already have the last version of FB Adapter that is `GoogleMobileAdsMediationFacebook (5.10.1.0)` (even after "pod update" I made today)

**Comment by chlandacastro** [comment]
HI Sotrosh,  The latest version  for Facebook Adapter is 6.3.1.0 https://developers.google.com/admob/ios/mediation/facebook#facebook-ios-mediation-adapter-changelog 
![Screen Shot 2021-04-20 at 11 26 43 AM](https://user-images.githubusercontent.com/59298836/115445910-53207080-a1cb-11eb-9a8e-5b30cda2db57.png)
and the latest Google Mobile Ad sdk is Google-Mobile-Ads-SDK (8.4.0)
Regards, 
Christian.

**Comment by sotrosh** [comment]
Thank you for response. I just found the same issue. When I do "pod install" or "pod update" it gets 5.10.1.0 version as the latest one even after deleting CocoaPods cache:

<img width="1009" alt="Screen Shot 2021-04-20 at 2 39 01 PM" src="https://user-images.githubusercontent.com/1019784/115447297-56752580-a1e6-11eb-9d15-5e8e097d2c7a.png">

**Comment by sotrosh** [comment]
Solved the problem by setting the exact version of Facebook Adapter:

> pod 'GoogleMobileAdsMediationFacebook', '~> 6.3'
