### ISSUE TITLE
Cannot find DTExchange ad network adapter

### ISSUE THREAD

**Issue by KevinTydlacka** [googleads/googleads-mobile-ios-mediation#417]
Xcode 14.3
Dependencies managed by cocoapods.
Google-Mobile-Ads-SDK 10.4.0
GoogleMobileAdsMediationFyber 8.2.1.0

We are integrating DT Exchange for the first time in our apps but the AdMob SDK cannot find the DT Exchange adapter. However, Ad Inspector shows the DT Exchange adapter is found and initialized.

Log message below
```
<Google> Cannot find an ad network adapter with the name(s): DTExchange. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
```
cocoapods is managing the dependencies and related build settings, but I verified that the Fyber Marketplace framework is linked and -ObjC is in Other Linker Flags. Additionally, other networks work fine.

**Comment by TomerFyber** [comment]
Hey @KevinTydlacka ,
Could you please provide some more info about the issue?

For example:
- The sample app where the error occurs
- Steps to reproduce the error
- App id (GADApplicationIdentifier)

This error might be shown when there are no ads to be shown, probably due to incorrect app/unit settings (worths trying other unit ids). 

Thanks!

**Comment by KevinTydlacka** [comment]
Thanks for the suggestion @TomerFyber. Ads loaded fine and the error wasn't present when I tested today...even though it was the same build as yesterday. Must have been some fill or back end config issue. I'll close this.
